# Generated by Django 4.1.3 on 2022-11-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=32)),
                ('attnumber', models.IntegerField(default=0)),
                ('batch', models.CharField(default='ELC', max_length=32)),
                ('totalclass', models.IntegerField(default=10)),
                ('attendancepercentage', models.IntegerField(default=0)),
                ('classtoattend', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('accounttype', models.CharField(max_length=16, verbose_name='accounttype')),
                ('classname', models.CharField(default='ELC', max_length=32, verbose_name='classname')),
                ('totalclass', models.IntegerField(default=10, verbose_name='totalclass')),
                ('attnumber', models.IntegerField(default=0, verbose_name='attendant class')),
                ('studentID', models.CharField(default='000', max_length=32, verbose_name='studentID')),
                ('cpassword', models.CharField(default=0, max_length=64, verbose_name='cpassword')),
            ],
        ),
    ]
