# Generated by Django 4.1.3 on 2022-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=32)),
                ('attnumber', models.IntegerField(default=0)),
                ('batch', models.CharField(default='ELC', max_length=32)),
                ('totalclass', models.IntegerField(default=10)),
                ('attendancepercentage', models.IntegerField(default=0)),
                ('classtoattend', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('accounttype', models.CharField(max_length=16)),
                ('classname', models.CharField(default='NULL', max_length=32)),
                ('totalclass', models.IntegerField(default=10)),
                ('attnumber', models.IntegerField(default=0)),
            ],
        ),
    ]
