# Generated by Django 4.1.3 on 2022-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cpassword',
            field=models.CharField(default='000', max_length=64, verbose_name='cpassword'),
        ),
    ]
