# Generated by Django 4.1.3 on 2022-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0002_alter_userinfo_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classname',
            field=models.CharField(default='000', max_length=32),
        ),
    ]
