# Generated by Django 4.1.3 on 2022-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='accounttype',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
