# Generated by Django 4.1.3 on 2022-11-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0003_rename_name_userinfo_username_remove_userinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=32)),
            ],
        ),
    ]
