# Generated by Django 4.1.3 on 2022-11-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0003_attendance_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='totalclass',
        ),
    ]
