# Generated by Django 4.1.3 on 2022-11-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='attandancenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='classnumber',
            field=models.CharField(default='NULL', max_length=32),
        ),
    ]
