# Generated by Django 4.1.3 on 2022-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0006_userinfo_cpassword_userinfo_totalclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendancepercentage',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attnumber',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='classtoattend',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='totalclass',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(default='NO', max_length=16, verbose_name='attendance'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2022-01-01', verbose_name='date'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='starttime',
            field=models.IntegerField(default=9, verbose_name='starttime'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classname',
            field=models.CharField(default='ELC', max_length=32, verbose_name='classname'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='studentID',
            field=models.CharField(default='000', max_length=32, verbose_name='studentID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cpassword',
            field=models.CharField(max_length=64, verbose_name='cpassword'),
        ),
    ]
